[versions]
agp = "8.11.2"
alarmee = "2.6.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.13.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.18.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.10.0"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.10.3"
junit = "4.13.2"
koalaplotCore = "0.11.2"
kotlin = "2.3.20"
material = "1.11.0"
material3 = "1.10.0-alpha05"
kotlinx-datetime = "0.7.1"  # ** ADDED **
androidx-navigation = "2.9.2" # ** ADDED for Navigation **
kotlinxSerializationJson = "1.10.0" # ** ADDED for Navigation **
materialIconsExtended = "1.7.3"
room = "2.8.4" # **ADDED** for Room database
sqlite = "2.6.2" # **ADDED** for Room database
ksp = "2.3.6" # **ADDED** for Room database
vico = "3.1.0"

[libraries]
alarmee = { module = "io.github.tweener:alarmee", version.ref = "alarmee" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplotCore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" } # ** ADDED for Navigation **
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" } # ** ADDED for Navigation **
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }  # ** ADDED **
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }  # **ADDED** for Room database
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }  # **ADDED** for Room database
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }  # **ADDED** for Room database
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }  # **ADDED** for Room database
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
# Compose Multiplatform
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
# Material 2 theming in Compose Multiplatform
vico-compose-m2 = { group = "com.patrykandpatrick.vico", name = "compose-m2", version.ref = "vico" }
# Material 3 theming in Compose Multiplatform
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
# Android view system
vico-views = { group = "com.patrykandpatrick.vico", name = "views", version.ref = "vico" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" } # ** ADDED for Navigation **
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }  # **ADDED** for Room database
androidx-room = { id = "androidx.room", version.ref = "room" }  # **ADDED** for Room database
